### ISSUE TITLE
DirectShowPlayerService::doRender: Unresolved error code 80040266

### ISSUE THREAD

**Issue by qyvlik** [qyvlik/Flat.qml#4]
当你发布的qmlproject包含QtMultimedia模块时，运行在一个干净的系统上时，要注意，随时播放失败，因为QtMultimedia使用的系统默认的音视频编/解码器，如果系统没有安装与qt对应的音视频编解码器的话，就会出现

```
DirectShowPlayerService::doRender: Unresolved error code ****
```

如上诉的错误提示
查看相关的文章

> [here](http://tiku.io/questions/3451444/qmediaplayer-resource-error)
> 
> [here](https://support.microsoft.com/zh-cn/kb/886273)
> 
> [here](https://www.mail-archive.com/qt-mobility-feedback@qt.nokia.com/msg00343.html)
> 
> [here](http://blog.gmane.org/gmane.comp.lib.qt.mobility.general/month=20111001)
> 
> [here](http://www.4byte.cn/question/473398/qmultimedia-which-video-audio-encodings-and-containers-are-supported.html)
> 
> [here](http://stackoverflow.com/questions/18884503/qmultimedia-which-video-audio-encodings-and-containers-are-supported)

这个问题从qt4开始到qt5.5，因为新的qt5的QtMultimedia模块会直接使用GStream ，但是为何不使用FFmpeg呢？

**Comment by qyvlik** [comment]
# 解决办法是安装 **LAV Filters**

[LAV Filters](http://forum.doom9.org/showthread.php?t=156191)

[LAV Filters download](http://files.1f0.de/lavf/LAVFilters-0.65.exe)

**Comment by Kairo-Dai** [comment]
WIn10 周年更新版安装后解决了这个问题

**Comment by Fydui** [comment]
谢谢谢谢..............正好碰到DirectShowPlayerService::doRender: Unresolved error code这个问题

**Comment by qyvlik** [comment]
@Fydui 
升级为win10吧。

**Comment by DreamLife-Jianwei** [comment]
菜鸟表示win10编写还是遇到这个问题了

**Comment by qyvlik** [comment]
@DreamLifeOffice 这就尴尬了，Qt 版本呢？

**Comment by shencang** [comment]
同样问题= =qt5.10  win10

**Comment by xuweixi10** [comment]
还是要安装解码器的。

**Comment by omgdo** [comment]
遇到了这个问题 打卡签到

**Comment by 852850353** [comment]
安装了还是不行

**Comment by xuweixi10** [comment]
如果没安装是一个都不可以还是部分不可以。

**Comment by omgdo** [comment]
> 安装了还是不行

那不是很难受呀？

**Comment by omgdo** [comment]
> 如果没安装是一个都不可以还是部分不可以。

没安装部分可以

**Comment by 852850353** [comment]
现在ok了

**Comment by omgdo** [comment]
> 现在好了

中间做了什么？

**Comment by 852850353** [comment]
安装到Qt下  就好了重启qt

**Comment by freedom01020** [comment]
唉，2020了，QT5.13.1，就算安装了还是不行

**Comment by qyvlik** [comment]
@freedom01020  try QtAV

**Comment by sbbug** [comment]
OS:win10  
after installing LAV Filters ,it is ok

**Comment by Ultcrt** [comment]
谢谢，PyQt5在安装LAV Filters后能够正常使用了

**Comment by children2018** [comment]
qt creator 4.3.1

**Comment by children2018** [comment]
qt creator 4.3.1
based on qt5.9
msvc 2015 ,,32bit
2021年，安装了LAVFilters-0.65.exe之后，立马能播放日文、中文名字歌曲了（我连界面都没关）。
只能帮到这儿了，但是QT会自动把这个插件打包进去？？我不知道

**Comment by qyvlik** [comment]
@children2018 不会将这个插件进行打包。

**Comment by xw27** [comment]
Thanks, as a QT rookie, I learned
